### ISSUE TITLE
Должно быть 1.8

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/Week2HomeworkCallularPlan#2]
https://github.com/AlekseiILitvinov/Week2HomeworkCallularPlan/blob/b6f1aa61de4c04e885a4c3e8490a4520a5419f85/pom.xml#L12-L13

**Comment by AlekseiILitvinov** [comment]
Возможно, я что-то не так настроил на моем ноутбуке, но у меня Maven воспринимает версию только так. Я писал туда 1.8, но система продолжает использовать правила для 1.5.

**Comment by coursar** [comment]
Обновите через боковую панель Maven
